### ISSUE TITLE
Fix TCP/IP db connection

### ISSUE THREAD

**Issue by danypr92** [coopdevs/coopdevs-provisioning#10]
El 15 de noviembre dejo de funcionar el servicio por problemas de conectividad con la base de datos:

`15/Nov/2017:10:32:07 +0000 "GET /index.php?r=survey/index&sid=549217" 500 /opt/sites/limesurvey/index.php 108.483 2048 18.44%`

Comprobamos que el anattended-upgrade habia actualizado los paquetes de Postgres:

```
Start-Date: 2017-11-15  07:23:36
Commandline: /usr/bin/unattended-upgrade
Upgrade: postgresql-client-9.5:amd64 (9.5.9-0ubuntu0.16.04, 9.5.10-0ubuntu0.16.04), libpq5:amd64 (9.5.9-0ubuntu0.16.04, 9.5.10-0ubuntu0.16.04), libpq-dev:amd64 (9.5.9-0ubuntu0.16.04, 9.5.10-0ubuntu0.16.04), postgresql-9.5:amd64 (9.5.9-0ubuntu0.16.04, 9.5.10-0ubuntu0.16.04), postgresql-contrib-9.5:amd64 (9.5.9-0ubuntu0.16.04, 9.5.10-0ubuntu0.16.04)
End-Date: 2017-11-15  07:23:47
```

Tras esta nueva actualización es necesario añadir una conexión para IPv6 al archivo `pg_hba.conf`:

`host limesurvey limesurvey ::1/32   md5 `

Falta investigar que paquete provoca el fallo y si se puede volver a repetir. 

Se podria añadir a la whitelist del `unattended-upgrade`: https://help.ubuntu.com/lts/serverguide/automatic-updates.html

**TODO**

- [ ] Investigar error y asegurar que es solo la actualización del 
- [ ] Proponer modificación para evitarlo en el futuro.
- [ ] Añadir modificación al rol adecuado.
